package constants

const (
	SIGNAL_TAKE_SESSION = "TAKE"
	SIGNAL_END_SESSION  = "END SESSION"
	SIGNAL_BANNED       = "BANNED CLIENT"
	SIGNAL_MOVE_SESSION = "MOVE SESSION"
	SIGNAL_NEED_SUPPORT = "NEED SUPPORT"
)
