# name: Deploy to DigitalOcean

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     env:
#       DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#       DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
#       DIGITALOCEAN_SSH_KEY: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
#       DIGITALOCEAN_VM_IP: ${{ secrets.DIGITALOCEAN_VM_IP }}
#       IMAGE_TAG: "latest"
#       APP_NAME: "websocket-chat"
#       IMAGE_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/websocket-chat:latest"

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up SSH
#       uses: webfactory/ssh-agent@v0.5.3
#       with:
#         ssh-private-key: ${{ env.DIGITALOCEAN_SSH_KEY }}

#     - name: Build Docker image
#       run: docker build -t $IMAGE_NAME .

#     - name: Push Docker image to DockerHub
#       run: |
#         echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
#         docker push $IMAGE_NAME

#     - name: Deploy to DigitalOcean
#       run: |
#         ssh -o StrictHostKeyChecking=no root@${{ env.DIGITALOCEAN_VM_IP }} << EOF
#           docker pull $IMAGE_NAME
#           docker stop $APP_NAME || true
#           docker rm $APP_NAME || true
#           docker run -d --name $APP_NAME --restart always -p 8080:8080 $IMAGE_NAME
#         EOF
